/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as GarageRouteImport } from './routes/garage'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecordRouteImport } from './routes/record'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as UploadVideoRouteImport } from './routes/upload-video'
import { Route as VehicleSetupRouteImport } from './routes/vehicle-setup'
import { Route as HistoryIndexRouteImport } from './routes/history.index'
import { Route as HistorySessionIdRouteImport } from './routes/history.$sessionId'
import { Route as ResultFindingIdRouteImport } from './routes/result.$findingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageRoute = GarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadVideoRoute = UploadVideoRouteImport.update({
  id: '/upload-video',
  path: '/upload-video',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleSetupRoute = VehicleSetupRouteImport.update({
  id: '/vehicle-setup',
  path: '/vehicle-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorySessionIdRoute = HistorySessionIdRouteImport.update({
  id: '/history/$sessionId',
  path: '/history/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultFindingIdRoute = ResultFindingIdRouteImport.update({
  id: '/result/$findingId',
  path: '/result/$findingId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/chat': typeof ChatRoute
  '/garage': typeof GarageRoute
  '/home': typeof HomeRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/record': typeof RecordRoute
  '/signup': typeof SignupRoute
  '/summary': typeof SummaryRoute
  '/upload-video': typeof UploadVideoRoute
  '/vehicle-setup': typeof VehicleSetupRoute
  '/history/$sessionId': typeof HistorySessionIdRoute
  '/result/$findingId': typeof ResultFindingIdRoute
  '/history/': typeof HistoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/chat': typeof ChatRoute
  '/garage': typeof GarageRoute
  '/home': typeof HomeRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/record': typeof RecordRoute
  '/signup': typeof SignupRoute
  '/summary': typeof SummaryRoute
  '/upload-video': typeof UploadVideoRoute
  '/vehicle-setup': typeof VehicleSetupRoute
  '/history/$sessionId': typeof HistorySessionIdRoute
  '/result/$findingId': typeof ResultFindingIdRoute
  '/history': typeof HistoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/chat': typeof ChatRoute
  '/garage': typeof GarageRoute
  '/home': typeof HomeRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/record': typeof RecordRoute
  '/signup': typeof SignupRoute
  '/summary': typeof SummaryRoute
  '/upload-video': typeof UploadVideoRoute
  '/vehicle-setup': typeof VehicleSetupRoute
  '/history/$sessionId': typeof HistorySessionIdRoute
  '/result/$findingId': typeof ResultFindingIdRoute
  '/history/': typeof HistoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capture'
    | '/chat'
    | '/garage'
    | '/home'
    | '/live'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/record'
    | '/signup'
    | '/summary'
    | '/upload-video'
    | '/vehicle-setup'
    | '/history/$sessionId'
    | '/result/$findingId'
    | '/history/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capture'
    | '/chat'
    | '/garage'
    | '/home'
    | '/live'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/record'
    | '/signup'
    | '/summary'
    | '/upload-video'
    | '/vehicle-setup'
    | '/history/$sessionId'
    | '/result/$findingId'
    | '/history'
  id:
    | '__root__'
    | '/'
    | '/capture'
    | '/chat'
    | '/garage'
    | '/home'
    | '/live'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/record'
    | '/signup'
    | '/summary'
    | '/upload-video'
    | '/vehicle-setup'
    | '/history/$sessionId'
    | '/result/$findingId'
    | '/history/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptureRoute: typeof CaptureRoute
  ChatRoute: typeof ChatRoute
  GarageRoute: typeof GarageRoute
  HomeRoute: typeof HomeRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  RecordRoute: typeof RecordRoute
  SignupRoute: typeof SignupRoute
  SummaryRoute: typeof SummaryRoute
  UploadVideoRoute: typeof UploadVideoRoute
  VehicleSetupRoute: typeof VehicleSetupRoute
  HistorySessionIdRoute: typeof HistorySessionIdRoute
  ResultFindingIdRoute: typeof ResultFindingIdRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage': {
      id: '/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof GarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload-video': {
      id: '/upload-video'
      path: '/upload-video'
      fullPath: '/upload-video'
      preLoaderRoute: typeof UploadVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle-setup': {
      id: '/vehicle-setup'
      path: '/vehicle-setup'
      fullPath: '/vehicle-setup'
      preLoaderRoute: typeof VehicleSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$sessionId': {
      id: '/history/$sessionId'
      path: '/history/$sessionId'
      fullPath: '/history/$sessionId'
      preLoaderRoute: typeof HistorySessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$findingId': {
      id: '/result/$findingId'
      path: '/result/$findingId'
      fullPath: '/result/$findingId'
      preLoaderRoute: typeof ResultFindingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptureRoute: CaptureRoute,
  ChatRoute: ChatRoute,
  GarageRoute: GarageRoute,
  HomeRoute: HomeRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  RecordRoute: RecordRoute,
  SignupRoute: SignupRoute,
  SummaryRoute: SummaryRoute,
  UploadVideoRoute: UploadVideoRoute,
  VehicleSetupRoute: VehicleSetupRoute,
  HistorySessionIdRoute: HistorySessionIdRoute,
  ResultFindingIdRoute: ResultFindingIdRoute,
  HistoryIndexRoute: HistoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
